# DEVELOPMENT FILE: This file is excluded from the final build.

# If present will push throughput and performance metrics to Ganglia
#gangila:
#  port:
#  server:

#Cache2k config
cache:
  expireAfterWrite: 3600000
  entryCapacity: 1000000
  refreshAhead: true

es:
  index: occurrence
  hosts: http://c3n1.gbif.org:9200/,http://c3n2.gbif.org:9200/

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
  cloud:
    zookeeper:
      enabled: false
      discovery:
        enabled: false
