# DEVELOPMENT FILE: This file is excluded from the final build.

# If present will push throughput and performance metrics to Ganglia
#gangila:
#  port:
#  server:

#Cache2k config
cache:
  expireAfterWrite: ${metrics.cache.expireAfterWrite}
  entryCapacity: ${metrics.cache.entryCapacity}
  refreshAhead: ${metrics.cache.refreshAhead}

es:
  index: ${metrics.es.index}
  hosts: ${metrics.es.hosts}
