/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.gbif.metrics.cube.tile.io;  
@SuppressWarnings("all")
public class LocationsAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LocationsAvro\",\"namespace\":\"org.gbif.metrics.cube.tile.io\",\"fields\":[{\"name\":\"locations\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"LocationAvro\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"lat\",\"type\":\"double\"},{\"name\":\"lng\",\"type\":\"double\"}]}}]}]}");
  @Deprecated public java.util.List<org.gbif.metrics.cube.tile.io.LocationAvro> locations;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return locations;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: locations = (java.util.List<org.gbif.metrics.cube.tile.io.LocationAvro>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'locations' field.
   */
  public java.util.List<org.gbif.metrics.cube.tile.io.LocationAvro> getLocations() {
    return locations;
  }

  /**
   * Sets the value of the 'locations' field.
   * @param value the value to set.
   */
  public void setLocations(java.util.List<org.gbif.metrics.cube.tile.io.LocationAvro> value) {
    this.locations = value;
  }

  /** Creates a new LocationsAvro RecordBuilder */
  public static org.gbif.metrics.cube.tile.io.LocationsAvro.Builder newBuilder() {
    return new org.gbif.metrics.cube.tile.io.LocationsAvro.Builder();
  }
  
  /** Creates a new LocationsAvro RecordBuilder by copying an existing Builder */
  public static org.gbif.metrics.cube.tile.io.LocationsAvro.Builder newBuilder(org.gbif.metrics.cube.tile.io.LocationsAvro.Builder other) {
    return new org.gbif.metrics.cube.tile.io.LocationsAvro.Builder(other);
  }
  
  /** Creates a new LocationsAvro RecordBuilder by copying an existing LocationsAvro instance */
  public static org.gbif.metrics.cube.tile.io.LocationsAvro.Builder newBuilder(org.gbif.metrics.cube.tile.io.LocationsAvro other) {
    return new org.gbif.metrics.cube.tile.io.LocationsAvro.Builder(other);
  }
  
  /**
   * RecordBuilder for LocationsAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LocationsAvro>
    implements org.apache.avro.data.RecordBuilder<LocationsAvro> {

    private java.util.List<org.gbif.metrics.cube.tile.io.LocationAvro> locations;

    /** Creates a new Builder */
    private Builder() {
      super(org.gbif.metrics.cube.tile.io.LocationsAvro.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.gbif.metrics.cube.tile.io.LocationsAvro.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing LocationsAvro instance */
    private Builder(org.gbif.metrics.cube.tile.io.LocationsAvro other) {
            super(org.gbif.metrics.cube.tile.io.LocationsAvro.SCHEMA$);
      if (isValidValue(fields()[0], other.locations)) {
        this.locations = (java.util.List<org.gbif.metrics.cube.tile.io.LocationAvro>) data().deepCopy(fields()[0].schema(), other.locations);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'locations' field */
    public java.util.List<org.gbif.metrics.cube.tile.io.LocationAvro> getLocations() {
      return locations;
    }
    
    /** Sets the value of the 'locations' field */
    public org.gbif.metrics.cube.tile.io.LocationsAvro.Builder setLocations(java.util.List<org.gbif.metrics.cube.tile.io.LocationAvro> value) {
      validate(fields()[0], value);
      this.locations = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'locations' field has been set */
    public boolean hasLocations() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'locations' field */
    public org.gbif.metrics.cube.tile.io.LocationsAvro.Builder clearLocations() {
      locations = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public LocationsAvro build() {
      try {
        LocationsAvro record = new LocationsAvro();
        record.locations = fieldSetFlags()[0] ? this.locations : (java.util.List<org.gbif.metrics.cube.tile.io.LocationAvro>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
